export enum tagTypes {
  user = "user",
  jobs = "jobs",
  company = "company",
  blog = "blog",
  faq = "faq",
  education = "education",
  workExperience = "workExperience",
  jobResponsibility = "jobResponsibility",
  training = "training",
  project = "project",
  skill = "skill",
  portfolio = "portfolio",
  event = "event",
  myApplication = "applied-job",
}

export const tagTypesList = [
  tagTypes.user,
  tagTypes.jobs,
  tagTypes.company,
  tagTypes.blog,
  tagTypes.faq,
  tagTypes.education,
  tagTypes.workExperience,
  tagTypes.jobResponsibility,
  tagTypes.training,
  tagTypes.project,
  tagTypes.skill,
  tagTypes.portfolio,
  tagTypes.event,
  tagTypes.myApplication,
];
