import Providers from "@/lib/Providers";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { AOSProvider } from "./AOSProvider";
import "./globals.css";

const inter = Roboto({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Career Connect Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>
          <AOSProvider>
            {/* <NavBar /> */}
            {children}
            {/* <Footer /> */}
          </AOSProvider>
        </body>
      </html>
    </Providers>
  );
}
